# Generated by Django 4.1.7 on 2023-02-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_title', models.CharField(max_length=50, verbose_name='Имя файла')),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
